# Generated by Django 5.2.8 on 2025-11-20 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('tournament_winner', 'Tournament Winner'), ('runner_up', 'Runner-Up'), ('top_scorer', 'Top Scorer'), ('best_defence', 'Best Defence'), ('unbeaten_streak', '10-Match Unbeaten'), ('fastest_goal', 'Fastest Goal'), ('player_of_week', 'Player of the Week'), ('custom', 'Custom Badge')], max_length=25)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('is_automatic', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy_type', models.CharField(choices=[('gold', 'Gold Trophy'), ('silver', 'Silver Trophy'), ('bronze', 'Bronze Trophy')], max_length=10)),
                ('position', models.IntegerField()),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Trophies',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='achievements.badge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='players.player')),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
    ]
