# Generated by Django 5.2.8 on 2025-11-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbadge',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges_awarded', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='teams.team'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='tournaments.tournament'),
        ),
    ]
