# Generated by Django 5.2.8 on 2025-11-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPostponement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_accepted', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('proposed_date', models.DateField()),
                ('proposed_time', models.TimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted_by_opponent', 'Accepted by Opponent'), ('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=25)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendlyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open for Acceptance'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_friendlies', to='teams.team')),
                ('opponent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_friendlies', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ready_pending', 'Waiting for Ready Confirmation'), ('creating_game', 'Home Team Creating Game'), ('waiting_join', 'Waiting for Away Team to Join'), ('in_progress', 'In Progress'), ('awaiting_highlight', 'Awaiting Highlights'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('home_forfeit', 'Home Team Forfeit'), ('away_forfeit', 'Away Team Forfeit'), ('both_forfeit', 'Both Teams Forfeit'), ('postponed', 'Postponed')], default='scheduled', max_length=25)),
                ('home_ready', models.BooleanField(default=False)),
                ('away_ready', models.BooleanField(default=False)),
                ('ready_time_start', models.DateTimeField(blank=True, null=True)),
                ('game_code', models.CharField(blank=True, max_length=50)),
                ('game_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['match_date', 'match_time'],
            },
        ),
    ]
