# Generated by Django 6.0 on 2026-01-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ready_pending', 'Waiting for Ready Confirmation'), ('in_progress', 'In Progress'), ('awaiting_highlight', 'Awaiting Highlights'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('home_forfeit', 'Home Team Forfeit'), ('away_forfeit', 'Away Team Forfeit'), ('both_forfeit', 'Both Teams Forfeit'), ('postponed', 'Postponed')], default='scheduled', max_length=25),
        ),
    ]
