# Generated by Django 5.2.8 on 2026-01-14 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='aggregate_away_score',
            field=models.IntegerField(blank=True, help_text='Aggregate score for two-leg knockout ties', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='aggregate_home_score',
            field=models.IntegerField(blank=True, help_text='Aggregate score for two-leg knockout ties', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='feeder_match_1',
            field=models.ForeignKey(blank=True, help_text='First match that feeds into this match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_to_1', to='matches.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='feeder_match_2',
            field=models.ForeignKey(blank=True, help_text='Second match that feeds into this match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_to_2', to='matches.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='knockout_round',
            field=models.CharField(blank=True, choices=[('round_of_32', 'Round of 32'), ('round_of_16', 'Round of 16'), ('quarter_final', 'Quarter-finals'), ('semi_final', 'Semi-finals'), ('final', 'Final')], help_text='Knockout stage round (e.g., Quarter-finals, Semi-finals)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, help_text='The match that the winner of this match advances to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='matches.match'),
        ),
    ]
