# Generated by Django 5.2.8 on 2026-01-14 19:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_tournament_scheduling_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_summary',
            field=models.TextField(blank=True, help_text='Written summary of the match'),
        ),
        migrations.AddField(
            model_name='match',
            name='summary_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image attachment for match summary', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='match',
            name='summary_video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Video attachment for match summary', max_length=255, null=True, verbose_name='video'),
        ),
    ]
