# Generated by Django 5.2.8 on 2026-01-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='squad_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_squads/'),
        ),
    ]
