# Generated by Django 5.2.8 on 2025-11-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by_side', models.CharField(choices=[('home', 'Home Team'), ('away', 'Away Team')], max_length=10)),
                ('video_file', models.FileField(upload_to='highlights/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='highlight_thumbnails/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending_verification', max_length=25)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
