# Generated by Django 5.2.8 on 2025-11-20 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('highlights', '0001_initial'),
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='matches.match'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='uploaded_by_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_highlights', to='teams.team'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_highlights', to=settings.AUTH_USER_MODEL),
        ),
    ]
