# Generated by Django 6.0 on 2026-01-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='evidence_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='highlights/screenshots/'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='video_url',
            field=models.URLField(blank=True, help_text='External link to YouTube/Twitch', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='highlights/videos/'),
        ),
    ]
