# Generated by Django 5.2.8 on 2025-11-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tournament_type', models.CharField(choices=[('league', 'League Format'), ('knockout', 'Knockout Format'), ('group_stage', 'Group Stage Format'), ('mixed', 'Mixed Format'), ('champions_league', 'eFootball Champions League')], max_length=20)),
                ('team_limit', models.IntegerField()),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize', models.TextField(blank=True)),
                ('rules', models.TextField()),
                ('status', models.CharField(choices=[('registration', 'Registration Open'), ('locked', 'Registration Locked'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registration', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('default_match_time', models.TimeField(default='17:00:00')),
                ('promotion_relegation_enabled', models.BooleanField(default=False)),
                ('teams_to_promote', models.IntegerField(default=2)),
                ('teams_to_relegate', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('junior_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_league', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('form', models.CharField(blank=True, max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-points', '-goals_for', 'goals_against'],
                'unique_together': {('tournament', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_verified', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['registered_at'],
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
