# Generated by Django 5.2.8 on 2025-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fixtures_generated',
            field=models.BooleanField(default=False),
        ),
    ]
