# Generated by Django 5.2.8 on 2026-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_add_scheduling_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='allowed_weekdays',
            field=models.CharField(blank=True, help_text='Allowed weekdays for matches (auto-populated based on tournament type)', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='priority',
            field=models.IntegerField(default=3, help_text='Competition priority for scheduling conflicts. Lower number = higher priority. Champions Cup=1, Cups=2, Leagues=3'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_robin_type',
            field=models.CharField(choices=[('single', 'Single Round Robin'), ('double', 'Double Round Robin')], default='double', help_text='Single: each team plays once | Double: each team plays home and away', max_length=10),
        ),
    ]
